# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "02955c49-e335-4ead-a2af-188273f1639a"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
  build_android_app(task: "assembleRelease")

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "8971b3733a2fd699ebd101e18ce228d80baeab92",
    build_secret: "88ba4d6880340c6e16c2690f626c60dcedff2e3a38650f2a8fb206f22f3e62d8"
  )
end
